### ISSUE TITLE
geneFoldChange returns NaN without warning

### ISSUE THREAD

**Issue by nzxwang** [DJFernandes/ABIgeneRMINC#1]
if the intersection of (stats at the tgt.thresh) and (gene) only has voxels of value -1, geneFoldChange will return value NaN. Maybe in this situation, it would be best to provide a warning to the user to avoid confusion?

**Comment by DJFernandes** [comment]
Sorry for the delay (I haven't checked github in a while).
The function now issues a warning when there are no voxels in target/contrast regions.

Thanks!
